//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralamamf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Araclar
    {
        public int Id { get; set; }
        public string AracMarka { get; set; }
        public string AracModel { get; set; }
        public string AracOzellik { get; set; }
        public string AracBakımGunu { get; set; }
        public int AracKm { get; set; }
        public string Hgs { get; set; }
        public decimal GunlukTutar { get; set; }
        public string AracKiraDurumu { get; set; }
    }
}
