//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralamamf
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AracKiralama1Container : DbContext
    {
        public AracKiralama1Container()
            : base("name=AracKiralama1Container")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Musteriler> Musteriler1 { get; set; }
        public virtual DbSet<Odemeler> Odemeler1 { get; set; }
        public virtual DbSet<Araclar> Araclar1 { get; set; }
        public virtual DbSet<Bayiler> Bayiler1 { get; set; }
        public virtual DbSet<Users> Users1 { get; set; }
    }
}
