//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arackiralamamf
{
    using System;
    using System.Collections.Generic;
    
    public partial class Musteriler
    {
        public int Id { get; set; }
        public string MusteriAdSoyad { get; set; }
        public string Telefon { get; set; }
        public string TcNo { get; set; }
        public string EhliyetDurumu { get; set; }
        public string Adres { get; set; }
    }
}
